#!/usr/bin/env bash

apps=(
    1password
    alfred
    applepi-baker
    atom
    bartender
    carbon-copy-cloner
    daisydisk
    fantastical
    firefox
    google-chrome
    google-drive
    hazel
    hipchat
    istat-menus
    iterm2
    little-snitch
    namebench
    ngrok
    screenflick
    skype
    the-unarchiver
    things
    vagrant
    virtualbox
    vlc
)

brew cask install ${apps[@]} --appdir=/Applications
