#!/usr/bin/env bash

formulae=(
    ansible
    awscli
    bash-completion
    battery
    cloc
    cmatrix
    dockutil
    dos2unix
    figlet
    gettext
    gitsh
    glib
    htop
    midnight-commander
    namebench
    rsync
    s-lang
    selenium-server-standalone
    spark
    speedtest_cli
    ssh-copy-id
    trash
    tree
    unixodbc
    wget
)

brew update
brew tap Goles/battery
brew tap homebrew/dupes
brew install ${formulae[@]}
