#!/usr/bin/env bash

# Adpated from thoughtbot's laptop script.
# https://github.com/thoughtbot/laptop

laptop_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n[LAPTOP] $fmt\\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/bin/" ]; then
  mkdir "$HOME/bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(which zsh)"

  laptop_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    laptop_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */zsh)
    if [ "$(which zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

if ! command -v brew >/dev/null; then
  laptop_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  laptop_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

laptop_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"

# Need to install openssl before libyaml
brew "openssl"
brew "openssl@1.1" # wget dependency

brew "autoconf" # asdf dependency
brew "automake" # asdf dependency
brew "awscli"
brew "bash"
brew "bash-completion"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "diff-so-fancy"
brew "dockutil"
brew "dos2unix"
brew "git"
brew "git-quick-stats"
brew "gmp" # Vim dependency
brew "gpg" # asdf-nodejs dependency
brew "hub"
brew "imagemagick"
brew "libtool" # asdf dependency
brew "libxslt" # asdf dependency
brew "libyaml" # asdf dependency
brew "mas"
brew "neovim", args: ["HEAD"]
brew "pandoc"
brew "perl"
brew "pgcli"
brew "postgresql", service_restart: :changed
brew "python"
brew "qt@5.5" if MacOS::Xcode.installed?
brew "readline"
brew "reattach-to-user-namespace"
brew "rsync"
brew "shellcheck"
brew "sqlite"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "thoughtbot/formulae/gitsh"
brew "tmux"
brew "tree"
brew "universal-ctags", args: ["HEAD"]
brew "unixodbc" # asdf dependency
# brew "vim" # Compiling myself these days.
brew "wget"
brew "xz"
brew "zsh"

# homebrew-cask
# https://github.com/caskroom/homebrew-cask
cask_args appdir: "/Applications"
cask "dash3"
cask "firefox"
cask "dropbox"
cask "fantastical"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "postico"
cask "skype"

# mas-cli
# https://github.com/mas-cli/mas
mas "1Password", id: 443987910
mas "Evernote", id: 406056744
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Things3", id: 904280696
mas "Tweetbot", id: 557168941
EOF

if brew list | grep --silent "qt@5.5"; then
  laptop_echo "Symlink qmake binary to /usr/local/bin for Capybara Webkit..."
  brew unlink qt@5.5
  brew link --force qt@5.5
fi

laptop_echo "Configuring asdf version manager..."
if [ ! -d "$HOME/.asdf" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.1
  append_to_zshrc "source $HOME/.asdf/asdf.sh" 1
fi

install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  fi
}

# shellcheck disable=SC1090
source "$HOME/.asdf/asdf.sh"
install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"

install_asdf_language() {
  local language="$1"
  local version
  version="$(asdf list-all "$language" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

laptop_echo "Installing latest Ruby..."
cat << EOF > "$HOME"/.default-gems
bundler
haml_lint
neovim
pry
rubocop
scss_lint
tmuxinator
EOF
install_asdf_language "ruby"
laptop_echo "Checking which Ruby and Gem installs we are using at this point..."
echo "Ruby --> $(which ruby)"
ruby -v
echo "Gem --> $(which gem)"
gem -v
gem update --system
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

laptop_echo "Installing latest Node..."
bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
install_asdf_language "nodejs"
echo "Node --> $(which node)"
node -v
echo "NPM --> $(which npm)"
npm -v

laptop_echo "Installing global Node packages..."
npm install -g eslint
npm install -g gulp-cli
npm install -g neovim
npm install -g svgo
